#!/usr/bin/osascript
on count_windows_on_current_space(process_name)
	tell application "System Events"
		tell process process_name
			return count of windows
		end tell
	end tell
end count_windows_on_current_space

repeat
	if count_windows_on_current_space("Google Chrome") ≠ 0 then
		try
			tell application "System Events" to tell process "Google Chrome" to perform action "AXRaise" of window 2
		end try
	end if
	delay 0.1
end repeat